### ISSUE TITLE
This version of WooCommerce Subscriptions - Renewal Only Coupon requires WooCommerce version 3.2 or newer.

### ISSUE THREAD

**Issue by shivams14** [Prospress/woocommerce-subscriptions-renewal-only-coupon#1]
Hi,
I want to give discount on my subscription products from first recurring renewal payment but I am suffering from this issue and not able to see renewal coupon fields in woocommerce -> settings -> subscriptions. I have updated the woocommerce plugin to 3.6 but it's still showing the error. What should I do to solve this issue or Is there any other way that I can give discount on subscription products from first recurring renewal payment in woocommerce subscription plugin.
Thanks,
Shivam Singla

**Comment by james-allan** [comment]
Hi @shivams14. 

The **WC Subscriptions Renewal Only Coupon** plugin allows you to create coupons which can only be used in manual renewal carts. 

It sounds like what you want is a coupon which just discounts the first renewal payment. At the moment, that's not possible with this plugin, WC Subscriptions, or any other plugin that I am aware of.

With Subscriptions you could create a limited recurring coupon (see [documentation](https://docs.woocommerce.com/document/subscriptions/store-manager-guide/#section-10)), but a limit of 1 payment would apply a discount to the initial purchase, and then be removed. A limit of 2 would apply to the initial purchase and then 1st renewal. I'm not sure if that would work for you.

But as far as I am aware, there isn't a coupon that can only be applied to the first renewal.

> This version of WooCommerce Subscriptions - Renewal Only Coupon requires WooCommerce version 3.2 or newer.
> I have updated the woocommerce plugin to 3.6 but it's still showing the error. 

Have you run the WooCommerce update? The plugin requires that the WooCommerce Database upgrade script has run. If you've updated to 3.6 and still seeing this error, my guess is that the database is out of date. You should see this notice. 

![](https://docs.woocommerce.com/wp-content/uploads/2015/02/data-update-notice-woocommerce.png)

You can find documentation on that here: https://docs.woocommerce.com/document/how-to-update-woocommerce/#section-11
