### ISSUE TITLE
Discount on Auto recurring payments in woocommerce subscriptions

### ISSUE THREAD

**Issue by shivams14** [Prospress/woocommerce-subscriptions-renewal-only-coupon#2]
Hello Sir,
I want to give discount on every auto recurring payments in woocommerce subscriptions plugin. Please guide me to do it.
I shall be very thankful to you.
Thanks & Regards,
Shivam Singla

**Comment by james-allan** [comment]
@shivams14 there isn't currently a way, that I am aware of, to apply a discount to automatic recurring payments through a UI.

If you have a developer or you're confident in writing your own custom code, you could do it using the filters available.
